export default function Head() {
  return (
    <>
      <title>Qurior</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
<<<<<<< Updated upstream
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon-v1.ico" />
=======
      <meta name="description" content="Cutting edge technology services" />
      <link rel="icon" href="/images/favicon.ico" />
>>>>>>> Stashed changes
    </>
  );
}
